[package]
name = "addon-depends-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
kodi-addon-logger = { path = "../kodi-addon-logger-rs" }
widevine-ffi = { git = "https://codeberg.org/dobo/widevine-rs.git", rev = "d36a1149aa59dc54f727715a10dd86ab66bccade" }
playready-ffi = "0.2.0"
