/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_WIDEVINE_FFI__
#define __RUST_WIDEVINE_FFI__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  Widevine CDM (Content Decryption Module)
 */
typedef struct widevine_cdm widevine_cdm_t;

/** \brief
 *  Creates new instance of [`Cdm`] from path to `.wvd` file.
 *
 *  When successful function returns pointer to [`Cdm`] which needs to be deallocated by [`widevine_cdm_free()`].
 *  Otherwise it returns `NULL` and pointer to `error_msg` that needs to be deallocated by [`widevine_error_message_free()`].
 */
widevine_cdm_t *
widevine_cdm_create_from_wvd (
    char const * wvd_path,
    char * * error_msg);

/** \brief
 *  Deallocates `cdm`. If `NULL` is passed function will do nothing.
 */
void
widevine_cdm_free (
    widevine_cdm_t * cdm);

/** \brief
 *  License request using the CDM
 */
typedef struct widevine_cdm_license_request widevine_cdm_license_request_t;


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {
    /** <No documentation available> */
    uint8_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_uint8_t;

/** \brief
 *  If successful it returns pointer to request challenge which needs to deallocated by [`widevine_challenge_free()`].
 *
 *  Otherwise it returns `NULL` and pointer to `error_msg` which needs to be deallocated by [`widevine_error_message_free()`].
 */
Vec_uint8_t
widevine_cdm_license_request_challenge (
    widevine_cdm_license_request_t const * request,
    char * * error_msg);

/** \brief
 *  Deallocates `request`. If `NULL` is passed function will do nothing.
 */
void
widevine_cdm_license_request_free (
    widevine_cdm_license_request_t * request);

/** \brief
 *  Session with the CDM
 */
typedef struct widevine_cdm_session widevine_cdm_session_t;

/** \brief
 *  Creates new [`CdmSession`].
 *  Return value should be passed to [`widevine_cdm_session_get_license_request()`] where it will be consumed (and deallocated).
 */
widevine_cdm_session_t *
widevine_cdm_open (
    widevine_cdm_t const * cdm);

/** \brief
 *  PSSH (Protection System Specific Header)
 *
 *  The PSSH object is used to identify the protected medium.
 */
typedef struct widevine_pssh widevine_pssh_t;

/** \brief
 *  Widevine license type
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum widevine_license_type {
    /** \brief
     *  Normal one-time-use license
     */
    WIDEVINE_LICENSE_TYPE_S_T_R_E_A_M_I_N_G,
    /** \brief
     *  Offline-use licence, usually for downloaded content
     */
    WIDEVINE_LICENSE_TYPE_O_F_F_L_I_N_E,
    /** \brief
     *  License type decision is left to provider
     */
    WIDEVINE_LICENSE_TYPE_A_U_T_O_M_A_T_I_C,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
widevine_license_type_t;

/** \brief
 *  Creates new [`CdmLicenseRequest`].
 *  It consumes `session` and `pssh`. It's recommended to set `session` and `pssh` to `NULL` after calling this function.
 *
 *  When successful it will return a pointer to [`CdmLicenseRequest`] which needs to be deallocated by [`widevine_cdm_license_request_free()`].
 *  Otherwise it will return `NULL` and pointer to error message in `error_msg` which needs to be deallocated by [`widevine_error_message_free()`].
 */
widevine_cdm_license_request_t *
widevine_cdm_session_get_license_request (
    widevine_cdm_session_t * session,
    widevine_pssh_t * pssh,
    widevine_license_type_t license_type,
    char * * error_msg);

/** \brief
 *  `&'lt [T]` but with a guaranteed `#[repr(C)]` layout.
 *
 *  # C layout (for some given type T)
 *
 *  ```c
 *  typedef struct {
 *  // Cannot be NULL
 *  T * ptr;
 *  size_t len;
 *  } slice_T;
 *  ```
 *
 *  # Nullable pointer?
 *
 *  If you want to support the above typedef, but where the `ptr` field is
 *  allowed to be `NULL` (with the contents of `len` then being undefined)
 *  use the `Option< slice_ptr<_> >` type.
 */
typedef struct slice_ref_uint8 {
    /** \brief
     *  Pointer to the first element (if any).
     */
    uint8_t const * ptr;

    /** \brief
     *  Element count
     */
    size_t len;
} slice_ref_uint8_t;

/** \brief
 *  Sets server certificate in [`CdmSession`].
 *
 *  When successful it will return new instance of [`CdmSession`].
 *  Otherwise it will return `NULL` and pointer to `error_msg` which needs to be deallocated by [`widevine_error_message_free()`].
 */
widevine_cdm_session_t *
widevine_cdm_session_set_service_certificate (
    widevine_cdm_session_t * session,
    slice_ref_uint8_t certificate,
    char * * error_msg);

/** \brief
 *  Deallocates `challenge`.
 */
void
widevine_challenge_free (
    Vec_uint8_t challenge);

typedef struct {
    uint8_t idx[16];
} uint8_16_array_t;

/** \brief
 *  Content key retrieved from CDM
 */
typedef struct widevine_content_key {
    /** \brief
     *  Key ID
     */
    uint8_16_array_t kid;

    /** \brief
     *  Key
     */
    Vec_uint8_t key;
} widevine_content_key_t;

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_widevine_content_key {
    /** <No documentation available> */
    widevine_content_key_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_widevine_content_key_t;

/** \brief
 *  Deallocates `keys`.
 */
void
widevine_content_keys_free (
    Vec_widevine_content_key_t keys);

/** \brief
 *  Deallocates `error_msg`. If `NULL` is passed function will do nothing.
 */
void
widevine_error_message_free (
    char * error_msg);

/** \brief
 *  Returns content keys from license message.
 *
 *  If successful (`error_msg` != `NULL`) return value needs to be deallocated by [`widevine_content_keys_free()`].
 *  Otherwise it returns `NULL` and pointer to `error_msg` which needs to be deallocated by [`widevine_error_message_free()`].
 */
Vec_widevine_content_key_t
widevine_license_request_get_content_keys (
    widevine_cdm_license_request_t const * request,
    slice_ref_uint8_t license_message,
    char * * error_msg);

/** \brief
 *  Deallocates `pssh`. If `NULL` is passed function will do nothing.
 */
void
widevine_pssh_free (
    widevine_pssh_t * pssh);

/** \brief
 *  Creates new instance of [`Pssh`] from Base64 string.
 *  Return value should be passed to [`widevine_cdm_session_get_license_request()`] where it will be consumed (and deallocated).
 *
 *  If not successful it will return `NULL` and pointer to `error_msg` which needs to be deallocated by [`widevine_error_message_free()`].
 */
widevine_pssh_t *
widevine_pssh_from_b64 (
    char const * b64,
    char * * error_msg);

/** \brief
 *  Creates new instance of [`Pssh`] from bytes.
 *  Return value should be passed to [`widevine_cdm_session_get_license_request()`] where it will be consumed (and deallocated).
 *
 *  If not successful it will return `NULL` and pointer to `error_msg` which needs to be deallocated by [`widevine_error_message_free()`].
 */
widevine_pssh_t *
widevine_pssh_from_bytes (
    slice_ref_uint8_t bytes,
    char * * error_msg);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_WIDEVINE_FFI__ */
